[theme]
base="light"
primaryColor="#b3b4b5"
backgroundColor="#fcfcfc"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[client]
showSidebarNavigation = false

runOnSave = true